{
 "title": "Water Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "sensor",
    "query": "import \"influxdata/influxdb/v1\"\r\n\r\nv1.tagValues(\r\n    bucket: \"water-monitoring\",\r\n    tag: \"sensor\",\r\n    predicate: (r) => true,\r\n    start: -1d\r\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Volume (L) of water consumed per sensor reading",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"water-monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"water-consumption\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"volume\")\r\n  |> filter(fn: (r) => r[\"sensor\"] =~ /${sensor:regex}/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Avg. flow rate (L/h) of water per sensor reading",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "litreh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"water-monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"water-consumption\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"flow-rate\")\r\n  |> filter(fn: (r) => r[\"sensor\"] =~ /${sensor:regex}/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Estimated water bill (PHP) per sensor reading",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyPHP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"water-monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"water-consumption\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"estimated-bill\")\r\n  |> filter(fn: (r) => r[\"sensor\"] =~ /${sensor:regex}/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Volume (L) of water consumed per sensor reading",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "query": "from(bucket: \"water-monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"water-consumption\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"volume\")\r\n  |> filter(fn: (r) => r[\"sensor\"] =~ /${sensor:regex}/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Flow rate (L/hr) of water per sensor reading",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "litreh" } },
   "targets": [
    {
     "query": "from(bucket: \"water-monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"water-consumption\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"flow-rate\")\r\n  |> filter(fn: (r) => r[\"sensor\"] =~ /${sensor:regex}/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Estimated water bill (PHP) per sensor reading",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyPHP" } },
   "targets": [
    {
     "query": "from(bucket: \"water-monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"water-consumption\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"estimated-bill\")\r\n  |> filter(fn: (r) => r[\"sensor\"] =~ /${sensor:regex}/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}